[tool.black]
target-version = ["py38"]
skip-string-normalization = true
exclude = '''
(
  /(
      \.git
    | \.mypy_cache
    | venv
    | migrations
    | allure-results
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 88
skip_glob = ["venv"]
combine_as_imports = true
combine_star = true